name: Create Repo - Validate
on:
  issues:
    types:
      - opened
      - edited
env:
  LGTM_TEAM: lgtm
jobs:
  validate:
    name: Validate issue
    runs-on: ubuntu-latest
    if: contains(github.event.issue.labels.*.name, 'createrepo') && github.event.issue.state == 'open'
    steps:
      - name: Validate
        uses: papaissad-sandbox-org/issueops-repo/validate@main
        with:
          authentication: app
          application-id: ${{ secrets.APP_ID }}
          application-private-key: ${{ secrets.APP_PEM }}
          team-assign: ${{ env.LGTM_TEAM }}
